name: Deploy Pipeline

on:
push:
branches: [ "main" ]

env:
FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
contents: write

jobs:
deploy:
runs-on: ubuntu-latest

```
steps:
  - name: Checkout repository code
    uses: actions/checkout@v4
    with:
      fetch-depth: 0

  - name: Setup Node.js
    uses: actions/setup-node@v4
    with:
      node-version: '22'
      cache: 'npm'

  - name: Install dependencies
    run: npm ci

  - name: Configure Git
    run: |
      git config --global user.name "github-actions[bot]"
      git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

  - name: Execute Pre-Deploy
    run: npm run predeploy

  - name: Execute Deploy
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    run: |
      git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/athom-dev/${{ github.repository }}.git
      npm run deploy
```
